name: Run npm test on macOS

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode-version: [15.4, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app

      - name: Run tests
        run: npm test
